sudo: required

services:
  - docker

script:
  - docker build -t arthurlockman/shell .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push arthurlockman/shell;
    fi
